# config.yml

# RPCs to use. Websockets required for realtime mode.
rpc:
  ethereum:
  avax: wss://ws-nd-244-501-601.p2pify.com/b9b145ce07d19551c170b9bb7bbff7ce/ext/bc/C/ws
  arbitrum: wss://arb-mainnet.g.alchemy.com/v2/uyZCOQfvmoJ8glOtYQVTMvAnOynKGTr0
  optimism:
  polygon:
  fantom:

# Postgres DB connection settings
postgres:
  host: 172.17.0.2
  user: chainreader
  password: chainreader
  name: postgres
